name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SWIFT_VERSION: "6.1.0"

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ env.SWIFT_VERSION }}
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: swift test
